### ISSUE TITLE
sata设备不识别

### ISSUE THREAD

**Issue by Oneashenzzx** [huzhimaye/Hackintosh_MS-H610ITX_I5-12400F_RX6750GRE#1]
老哥，你的sata固态或是机械识别正常吗，我无法识别到所有的sata设备，但是可以在hackintool里看到识别到了sata controller

**Comment by huzhimaye** [comment]
What kexts are you injecting?

**Comment by Oneashenzzx** [comment]
![kext](https://github.com/huzhimaye/Hackintosh_MS-H610ITX_I5-12400F_RX6750GRE/assets/134031308/e5e9a9d3-3400-4670-92ba-f3b1ebd15d30)
Thank you for your reply. The picture shows all the kext I have added

**Comment by huzhimaye** [comment]
Could you please try [CtlnaAHCIPort.kext](https://github.com/dortania/OpenCore-Install-Guide/blob/master/extra-files/CtlnaAHCIPort.kext.zip) as suggested by [Dortania's OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/userspace-issues.html#sata-drives-not-shown-in-diskutility)?

Posting your question on [reddit](https://www.reddit.com/r/hackintosh/) might also be helpful.

**Comment by Oneashenzzx** [comment]
Thanks man,I'll give it a try.
